---
title: "List of Finite Groups"
author: "Manu"
date: "3 March 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## hi

|Order|Factorisation|Groups|Complete|
|---|---|---|------|
|1|1|{e}|Yes|
|2|2|Z/2Z|Yes|
|3|3|Z/3Z|Yes|
|4|2*2|Z/4Z, Z/2Z^2|Yes|
|5|5|Z/5Z|Yes|
|6|2*3|Z/6Z, S3|Yes|
|7|7|Z/7Z|Yes|
|8|2\*2\*2|Z/8Z, Z/4Z x Z/2Z, Z/2Z^3, $D_4$, Criss|Yes|
|9|3*3|Z/9Z, $C(3)^2$|Yes|
|10|2*5|Z/10Z, $D_5$|Yes|
|11|11|Z/11Z|Yes|
|12|2\*2\*3|Z/12Z, C3, $D_6$||
|13|13|Z/13Z|Yes|
|14|2*7|Z/14Z, $D_7$||
|15|3*5|Z/15Z||
|16|2\*2\*2\*2|Z/16Z, $D_8$||
|17|17|Z/17Z|Yes|
|18|2\*3\*3|Z/18Z, $D_9$||
|19|19|Z/19Z|Yes|
|20|2\*2\*5|Z/20Z, $D_{10}$||
|21|3*7|Z/21Z||
|22|2*11|Z/22Z, $D_{11}$||
|23|23|Z/23Z|Yes|
|24|2\*2\*2\*3|Z/24Z, $C(4) \times C(2) \times C(3)$, $C(2)^3 \times C(3)$, S4, R, $D_{12}$||

## All groups of order 4

Let G be a group of order 4. If g has an element of order 4 then G is isomorphic to Z/4Z. Let's assume G doesn't have an element of order 4. All the elements of G must have order 1 or 2. That means all the elements of G exept the identity have order 2.
We write G = {e, a, b, c} where e is the identity and a,b and c have order 2.
$ab = ba \iff abab = e \iff (ab)^2 = e$ which is true since all elements of G have order 2. So we have shown that a and b commute. Furthermore 

* $<a> \cap <b> = {e}$ and
* ab = c because $ab=a \implies b = e$ so they generate G

Conclusion G is a direct-product $<a> \times <b> \sim (Z/2Z)^2$

## All groups of order 6

G a group of order 6

1. S3 is the only semi-direct product of C(3) and C(2) other than the direct product.
2. If G is abelian than G is isomorph to C(6)
3. If G is not abelian than G is a semi-direct product of C(3) and C(2)

Conclusion: C(6) and S3 are the only groups of order 6

**proof of 1**
Aut(C(3)) = C(2) which leaves 2 possibilities only for the direct product. The 2 possibilities are not isomorphic since one is abelian and the other is not.

**proof of 2**
From the structure of Abelian groups.

**proof of 3**
Let G be not abelian.

We know that:
- The elements of G have order 1, 2 or 3
- If the elements of a group have all order 2 then the group is abelian

So G has at least 1 element of order 3. We note it $k_0$ $<k_0>$ is normal since it's order in G is 2.

SO we have an exact sequence:

$$0 \rightarrow <k_0> \rightarrow G \rightarrow G/<k_0> \rightarrow 0$$

Let's take any element in the second class of G/<k0>. We call it s.

$s^2 \in <k_0>$ so s^2 has order 1 or 3. But s cannot have order 6 since the group is not Abelian. So s^2 = 1.

Now we have a map u that maps <k0> to e and s<k_0> to s. This is an homorphism and furthermore we have $\pi_{k_0}(u(q)) = q, \forall q \in G/<k_0>$. So this map splits the exact sequence and G is a direct product of C(3) by C(2).

This completes the proof.

## All Groups of order 8

Since Aut(C(4)) = C(2) there are 2 semi-direct products $C(2) \rtimes C(4)$.

### A Funny Group

Criss = $<r^4, s^4, s^2 = r^2, s^3rs = r^3>$

1. <r> is a normal group
  r and s generate this group. And we can see that the action of s on r leave it in the same group. So <r> is normal in Criss.
  
2. Criss/<r> has order 2 so Criss has 8 elements
  We can write any element g of Criss as a product $r^{i_1}s^{j_1} ... r^{i_n}s^{j_n}$
  We apply the projection onto r: $\pi_r(g) = \pi_r(r^{i_1}s^{j_1} ... r^{i_n}s^{j_n}) \\ = \pi_r(r)^{i_1}\pi_r(s)^{j_1} ... \pi_r(r)^{i_n}\pi_r(s)^{j_n} = \pi_r(s)^{\sum j_i}$
  So the quotient group is generated by [s]. We have $\pi(s^2) = <r>$ so the order of [s] is at most 2. It cannot be 1 because the conjugation relation imposes that s does not belong in the group generated by r.
  
We can verify that $s^3r^2s = r^2$ so that $<r^2>$ is normal as well. Criss/<r2> has order 4.
We have $\pi_2(r)^2 = 1$ and $\pi_2(s)^2 = 1$ and the class of r and s generate it. So $\mathrm{Criss}/<r^2> \sim C(2) \times C(2)$

The subgroup <r2> also commutes with every other element.

This is the table of this group.

|     | e   | r   | r2  | r3  | s   | sr  | sr2 | sr3 |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| e   | e   | r   | r2  | r3  | s   | sr  | sr2 | sr3 |
| r   | r   | r2  | r3  | e   | sr3 | s   | sr  | sr2 |
| r2  | r2  | r3  | e   | r   | sr2 | sr3 | s   | sr  |
| r3  | r3  | e   | r   | r2  | sr  | sr2 | sr3 | s   |
| s   | s   | sr  | sr2 | sr3 | r2  | r3  | e   | r   |
| sr  | sr  | sr2 | sr3 | s   | r   | r2  | r3  | e   |
| sr2 | sr2 | sr3 | s   | sr  | e   | r   | r2  | r3  |
| sr3 | sr3 | s   | sr  | sr2 | r3  | e   | r   | r2  |


### Proof

Let G be a non-Abelian group of order 8. The possible orders for the elements of G are 1, 2, 4 or 8. If all the elements of G are of order 2 then the group is commutative. Let r be an element of order 4.

<r> has index 2 in G so it is normal. Thus we have an exact sequence:

$$ 0 \rightarrow <r> \rightarrow G -> G/<r> \rightarrow 0$$

G/<r> has index 2. Let H be the other class of G/<r>. If that class has an element of order 2 then the above exact sequence splits and G is a semi-direct product. So all elements in this class have order 4. Let s be such an element.

We want to know what is the conjugation $s^3rs$. We know that it is in <r> and that it has order 4.
So it can be either r or $r^3$. If $s^3rs = r$ then r and s commute. But r and s generate G, so G is abelian, so we have a contradiction and $s^3rs = r^3$. So G is represented by $<r^4, s^4, s^2 = r^2, s^3rs = r^3>$ so G is the Criss group.


## All Groups of order 9

Aut(C(3)) = C(2). And there are no morphism from C(3) to C(2) execpt the identity. That means that there are no non-trivial semi-direct products of order 9.

1. We will show that G halways has a normal subgroup of order 3

Let G be an a group of order 9 that is not C(9). Let r be any element different of the identity. r has order 3. 
We also get a mapping:
$G \rightarrow \mathrm{Cl}(<r>)$ by $g \mapsto g^-1<r>g$
This defines a group action on the conjugacy classes of <r> in G. We get the following result:
$|Cl(<r>)| \times |Stab(<r>)| = |G| = 9$

So we have the following possibilities for the size of Cl(<r>) and Stab(<r>):

| |Cl(<r>)| | |Stab(<r>)| | Remark                                  |
|-----------|-------------|-----------------------------------------|
| 1         | 9           | In which case <r> is normal             |
| 3         | 3           |                                         |
| 9         | 1           | Impossible because r, r2 are in Stab<r> |

Let's suppose that $|Cl(<r>)| = 3$ then the action of G on <r> gives rise to a mapping:
$G \rightarrow S3$ and this mapping is not trivial. We can deduce that the Kernel of this application is a normal subgroup of order 3.

So G always has a normal subgroup of order 3

2. G is a semi-direct product

Let N be a normal subgroup of G of order 3. Let s in G such that sN generates G/N.
The mapping $G/N \rightarrow G$ which maps s to s is a group isomorphism that right splits the exact sequence:

$$0 \rightarrow N \rightarrow G \rightarrow G/N \rightarrow 0$$

So G is a semi-direct product.

## All Groups of order 10

We have Aut(C(5)) ~ C(4)

C(4) has 1 element of order 1, 1 element of order 2 and 2 elements of order 4.
So a mapping $C(2) \rightarrow C(4)$ maps either 
$$\begin{array}{ll} 1 \mapsto 1 \\
1 \mapsto 2\end{array}$$

Which gives only 2 possibilities. So there is only one non-trivial semi-direct product: $D_5$


Let G be a group of order 10. Let's show that it is a semi-direct product $C(2) \rtimes C(5)$
We can assume G to be non-Abelian. Then G must have an element of order 5 otherwise all its elements are of order 2 and it is abelian. Let's call r this element.
<r> is of index 2 in G so it is normal. Let s be an element of G so that s<r> is the other quotient class of G/<r>. We know that $s^2 \in <r>$ because the <r> is of index 2. So either $s^2 = e$ or s^2 is of order 5. But if s^2 is of order 5 then s is of order 10 and G = C(10) which we assumed wasn't. So $s^2 = e$ and we get a map $$G/<r> \mapsto G$$ that maps $s<r> \mapsto s$ and that right split the following exact sequence:

$$0 \rightarrow <r> \rightarrow G \rightarrow G/<r> \rightarrow 0$$

Hence $G = C(2) \rtimes C(5)$

## All groups of order 12

Let G be a group of order 12. Because it's prime factors are 2 and 3. Let H be a simple subgroup of G. Then |H| divide 12. So |H| = 1, 2, 3, 6, 12. According to the list of groups here we know that for H to be simple we need |H| = 2 and H = C(2) or |H| = 3 and H = C(3).

These are all the possibilities for the normal decomposition of G:

$$ C(3) \lhd C(2) \lhd C(2) \lhd G \\
C(2) \lhd C(3) \lhd C(2) \lhd G \\
C(2) \lhd C(2) \lhd C(3) \lhd G $$

## All groups of order 14

Example: 
D7 is a group of order 14, its elements are:
(0, 0) (0, 1) (0, 2) (0, 3) (0, 4) (0, 5) (0, 6)
(1, 0) (1, 1) (1, 2) (1, 3) (1, 4) (1, 5) (1, 6)

and 
(0, 1) . (1, 0) = (0, 6)
(0, 1) . (1, 1) = (0, 0)
(1, 0) . (0, 1) = (1, 1)

Let's show that all groups of order 14 are a semi-direct product. Let g be an element of G not equal to the identity.

* if the order of g is 2
  For example let's consider (1, 0) in D7 the left classes by (1, 0) are:
  (0, 0) (1, 0)
  (0, 1) (1, 6)
  (0, 2) (1, 5)
  (0, 3) (1, 4)
  (0, 4) (1, 3)
  (0, 5) (1, 2)
  (0, 6) (1, 1)
  There are 7 left classes
  
  Let's take any element of another class: (1, 3).
  (1, 3) ^ (1, 3) = (0, 0) So it has order 2
  But (0, 4) has order 7
  
  If now we consider (1, 3) the classes are:
  (0, 0) (1, 3)
  (0, 1) (1, 2)
  (0, 2) (1, 1)
  (0, 3) (1, 0)
  (0, 4) (1, 6)
  (0, 5) (1, 5)
  (0, 6) (1, 4)
  
* if the order of g is 14 then we consider g^2 of order 7.

Let A be the set of all element of order p. Conjugation sends all element of order p to an element of order p. So we have an action G -> Aut(A) 

|A| . |Stabx| = pq

The class of x under this action gives |Ox| . |Stabx| = pq
|Ox| = pq is not possible because the identity is not of order p.
So |Ox| = 1 or |Ox| = q, |Ox| = p 

In a group of order pq we have

|Ap| + |Aq| + 1 = pq

