---
title: "Group theory general"
author: "Manu"
date: "28 February 2017"
output:
  html_document: default
  pdf_document: default
header-includes: \usepackage{bbm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Group decomposition


Let G be a group, we assume

1. **H** is a normal subgroup.
2. $\kappa$ in **G/H** is normal in **G/H**

We write **K** be $\pi_H^{-1}\{\kappa\}$


Then

1. **K** is a normal subgroup of **G**
2. $G/K \sim \frac{G/H}{\kappa}$ or $\frac{G}{\kappa H} \sim \frac{G/H}{\kappa}$

## Other formulations

### Number 1: using $\kappa$
We have

$$ 0 \rightarrow H \rightarrow G \rightarrow G/H \rightarrow 0 $$


$$ 0 \rightarrow \kappa \rightarrow G/H \rightarrow \frac{G/H}{\kappa} \rightarrow 0 $$

then we can deduce


$$ 0 \rightarrow \pi_H^{-1}\{\kappa\} \rightarrow G \rightarrow \frac{G/H}{\kappa} \rightarrow 0 $$

### Number 2: using **K**

$$ 0 \rightarrow H \rightarrow G \rightarrow G/H \rightarrow 0 $$


$$ 0 \rightarrow KH \rightarrow G/H \rightarrow \frac{G/H}{KH} \rightarrow 0 $$

then we can deduce

$$ 0 \rightarrow K \rightarrow G \rightarrow \frac{G/H}{KH} \rightarrow 0 $$

## Proof

### Proof that **K** is normal in **G**

Let g \in **G** and k \in **K**
We want to show that $g^{-1}kg \in K$
$K=\pi_H^{-1}\{\kappa\}$ so we have
$$g^{-1}kg \in \pi_H^{-1}\{\kappa\} \iff \pi_H(g^{-1}kg) \in \kappa \iff \pi_H(g^{-1})\pi_H(k)\pi_H(g) \in \kappa$$


But $\pi_H(k) \in \kappa$ and since $\kappa$ is normal in **G/H** the last inclusion is true and we have proved that **K** is normal in **G**.

## Examples

## More group decomposition

I have a group G that I am trying to understand. I find a normal subgroup N in G.
Then I try to understand N and I try to understand G/N.
4 possibilities:

1. Both are simple
2. N is simple, G/N has a normal subgroup
3. N has a normal subgroup, G/N is simple
4. Both have normal subgroups

## Subset of Sn given by generators

Let's say that I have $g_1, \dots, g_k \in \mathrm{Sn}$ and I want to know the subgroup of Sn that they generate. That is I want to have a list of all the elements in $<g_1, \dots, g_k>$.

Finding a normal subgroup is useful for determining the number of elements in a group when we only know the generators. It is also useful for determining all the elements of said group.
For example let's say that I have a group generated by g, h. If I want to find all the elements one solution is to first take all the simple products:
e, g, h then compute
g2, gh, hg, h2 compare each with the first step (4*3 = 12 comparisons) if they are all inside the previous step then e, g, h forms a group. if not then commpute
g3, g2h, ghg, gh2, hg2, hgh, h3g, h3 if they are all in the previous steps (8*7 = 56 comparisons) then


### Examples

* When trying to understand S3 I find that <p> ~ Z/3Z is normal and that the quotient is ~ to Z/2Z. This is situation 1.

## Other examples of decompositions

* Z/4Z is a group of order 4. It has 4 elements {0, 1, 2, 3}. The subgroup {0, 2} is a normal subgroup (every subgroup is normal since the group is Abelian). The quotient has order 2 and so is isomorphic to Z/2Z. However Z/4Z is not a semi-direct product of {0, 2} since there are no other subgroups of order 2 inside Z/4Z.

The classes of (Z/4Z)/(Z/2Z) are {0, 2}, {1, 3}. 
The action of each element on the classes are:

| Z/4Z | {0, 2} | {1, 3} |
|------|--------|--------|
|  0   | {0, 2} | {1, 3} |
|  1   | {1, 3} | {2, 0} |
|  2   | {2, 0} | {3, 1} |
|  3   | {3, 1} | {0, 2} |

