---
title: "Ideas"
author: "Manu"
date: "February 28, 2018"
output:
    html_document:
        toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## [28/11/2020] Invariants and covariants of T2

Suggested program:

1. Revise the character orthonomality formula
2. Find all the characters and irreducible representations of $T_2 \sim D_4$
3. Using the average projector, find all the invariants of small degree.
4. Using the other projectors, find other co-variants of small degree.
5. Can these "natural words" be used in any meanigful way to describe the beats?

In order to find all the representations of T3 I can use the forget last layer morphism, which maps to T2. So that will give me 5 representations "for free". Forgetting the two last layer I get one for representation from T2. I still need a lot of representations to get up to 25.




## [25/11/2020] Thinking about natural words on S3

Found a few natural words to talk about triplets of numbers.

Besides the average, there is also a 2-dimensional triangle which is a covariant linear word. Here it is:

$$\begin{pmatrix}
    2x_1 - x_2 - x_3 \\
    \sqrt{3}(x_2-x_3)
    \end{pmatrix}
$$

It would be interesting to work more on this and try to see how we can use the natural language the retrieve the values of the triplets.

Since the two-dimensional word and the triangle are enough to recover the individual values of the triplets.
We could express a polynomial of order 3 as a function from triplets to triplets.
For most triangles, the polynomial cannot be expressed as a function of the words, because it breaks the symmetry?
Actually it does not break the symmetry. So it should be possible to express the polynomial operating on triangles as a function of the natural language.
Using this expression, is it easier to find the roots?

I could try it on the order 2 first.



## [23/11/2020] Focus of L1 in T3 for rythm representations

Until now, when I worked on representing tree groups as rythm, I was mostly focusing on the quaternion group, because it had 4-cycles and a cool structure.

I was able to generate some beats, however they don't seem to reflect the group structure that well.

It is very hard to use the quaternion group to count.

Maybe the issue is that the group is too complicated, or maybe it is not a natural group in this circumstance.

It would be interesting to focus of L1 inside of T3. The reason is that this group is very natural, it sits in the central series of T3. It is also abelian, so its central series is not too complicated.


What I could do:

1. Using the step as the identity beat, get a beat representation of L1.
2. Find all the iterated centers of T3 that are in L1.
3. Look at what this representation looks like modulo different centers of T3 contained in L1.


## Snowflakes

Snowflakes have symmetry. Their symmetry is interesting because it arises naturally from the simple natural phenomena. It is also very beautiful.

How to explain the symmetry?

How to explain the diversity of the patterns?

Is there any links to group theory?

It would be interesting to simulate a very simple snowflakes and trying to grow them in a simulation. The simulation might be oversimplified.

Resources about the simulation:

[Video of simulated snowflakes](https://www.youtube.com/watch?v=kEWYVCbOskQ)

[Software that can simulate snowflakes](http://softology.com.au/voc.htm)

[More information about simulating snowflakes](http://psoup.math.wisc.edu/Snowfakes.htm)