library(permutations)

#' Create a permutation from it's cycle decomposition.
#' @usage cyc(1:3, 4:6)
cyc <- function(...) {
  l <- list(...) # list of cycles
  acc <- as.cycle()
  for(cy in l)
    acc <- acc * as.cycle(cy)
  acc
}

to_vector <- function(l) {
  r <- c(as.cycle())
  for(el in l)
    r <- c(r, el)
  tail(r, -1)
}

#' Is the element in the group generated by el.
in_generated_group <- function(el, g) {
  # created a list containing all the elements of the group <g>
  group <- lapply(seq_len(permorder(g)), function(x) g^x)
  in_group <- FALSE
  for(iter_el in group)
    if(el == iter_el)
      in_group <- TRUE
  
  in_group
}

################################################################################
# Rubik's cube
# Front face
# 1 | 2
# 3 | 4
# Back face
# 5 | 6
# 7 | 8
# generators of the rubik's cube group
bg <- cyc(c(1, 5, 7, 3))
bd <- cyc(c(2, 6, 8, 4))
th <- cyc(c(1, 2, 6, 5))
tb <- cyc(c(3, 4, 8, 7))

################################################################################
# Products
# 4*3 = 12 possibilies but two are equals -> 10 products
prods <- c(
  bg * bd, # order 4
  th * tb, # order 4
  
  bg * th, # 5
  th * bg, # 5
  
  bd * tb, # 5
  tb * bd, # 5
  
  bg * tb, # 3
  tb * bg, # 3
  
  bd * th, # 3
  th * bd) # 3

# check that all the generated groups are distincts
prod_inclusions <- c(
  # order 4
  in_generated_group(el = bg * bd, g = th * tb),
  in_generated_group(el = (bg * bd)^2, g = th * tb),


  # order 5
  in_generated_group(el = bg * th, g = th * bg),
  in_generated_group(el = bg * th, g = bd * tb),
  in_generated_group(el = bg * th, g = tb * bd),
  
  in_generated_group(el = th * bg, g = bd * tb),
  in_generated_group(el = th * bg, g = tb * bd),
  
  in_generated_group(el = bd * tb, g = tb * bd),

  # order 3
  in_generated_group(el = bg * tb, g = tb * bg),
  in_generated_group(el = bg * tb, g = bd * th),
  in_generated_group(el = bg * tb, g = th * bd),
  
  in_generated_group(el = tb * bg, g = bd * th),
  in_generated_group(el = tb * bg, g = th * bd),
  
  in_generated_group(el = bd * th, g = th * bd)
)

################################################################################
# Conjugations
# 4*3 = 12 possibilies but 4 are already in the generators
# All have order 4
conj <- c(
  bd*bg/bd, # = bg
  th*bg/th,
  tb*bg/tb,
  
  th*bd/th,
  tb*bd/tb,
  bg*bd/bg,  # = bd
  
  bd*th/bd,
  tb*th/tb, # = th
  bg*th/bg,
  
  bd*tb/bd,
  th*tb/th, # tb
  bg*tb/bg
)