---
title: "T3"
author: "Emmanuel Blonkowski"
date: "11 July 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basics

T3 is the automorphism group of a binary tree of depth 4.

We have:
$T_3 = i_2(T_2) \ltimes L^3_3 \sim D_4 \ltimes C(2)^4$
Which means $T_3$ has 128 elements.

## Centers

### 1st Center

First center is of order 2 generated by z.


### 2nd Center

**Property** Any member $z_2$ of the second center verify $F(z_2) = 0$ or $F(z_2) = z_{T_2}$ (in $T_2$)

> 
**Proof**: We have the forget last layer morphism, which is surjective: $F: T_3 \rightarrow T_2$       
>
$\mathcal{Z} \subset \mathrm{Ker}(F)$, so F descend to the quotient:
>
$\bar F : T_3/\mathcal{Z} \rightarrow T_2$ and it is still surjective.
>
Surjective morphisms map centers to centers so $F(z_2) = \bar F(z_2) \in \mathcal{Z}(T_2)$


**Property** (0, z, 0) belongs to the second center.

> **Proof**: We verify directly with the action of the 3 standard generators.

## Action on Seq(n)

It acts on $C(2)^8$

According to the Pólya enumeration theorem, the number of orbits is given by:
$${1 \over 128} \times \sum_{g \in T_3} 2^{c(g)}$$

Burnside's lemma gives for the number of orbits:
$${1 \over 128} \times \sum_{g \in T_3} |X^g|$$



Those are the representents of equivalence classes of T2: 0(00), 0(11), 0(10), 1(00), 1(10)

## Decomposition Series

$$Z(T_3) \subset \mathrm{Ker}(F_3) \subset \mathrm{Ker}(F_3^2) \subset T_3$$

Which is a normal serie of T3.
We would like to extend it to a full decomposition series of T3.

$\mathrm{Ker}(F_3^2)$ is isomorphic to $T_2^2$ and has index 2 in T3 so it is maximal in T3.
Now we are looking for a maximal normal subgroup of $\mathrm{Ker}(F_3^2)$
This group has order 64 so a maximal normal subgroup must have order 32.
$L_2^2$ is maximal normal in $T_2$, so $L_2^2 \times L_2^2$ is also normal in $T2^2$
This subgroup corresponds to all elements of T3 of the form

$$Z(T_3) \subset \mathrm{Ker}(F_3) \subset F_3^{-1}\{Z(T_2)\} \subset \mathrm{Ker}(F_3^2) \subset T_3$$

Since the center is normal in T3 we have a map:
$T3 \rightarrow T3/Z_3$
$T3/Z_3$ has order 64. Multiplication by an element of the center

