---
title: "Translation Group of a Binary Function"
author: "Manu"
date: "4 June 2018"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction

Let $\mathcal{B} = \{0, 1 \}$ and let $F = \{f: \mathbb{R} \rightarrow \mathcal{B}\}$.

The **observation group** is the group of operations that leave a beat unchanged to the observer. We model this group on a real human listener. In our case there is only one operation, and it is time shift of the beat by any increment. Any other operation, such as changing the timing, inverting the recording can be heard by a human listener. Similarly, inverting the instruments (here the 0 and the 1) is also noticeable to our ears, so it is not in the observation group.

The observation group is $\mathbb{R}$ and it acts on F via the following action 
$$\bullet: F \times \mathbb{R} \rightarrow F \\ r \bullet t (x) \mapsto r(x + t) $$

To the observer, recordings that differ only by a time shift are identical and cannot be distinguished. So the observer is only interested in classes of equivalence of recordings that are shift-equivalent. Such equivalence classes are called **beats**, they are precisely the action of the observation group on F.

For any beat B, we can associate a unique subgroup S of $\mathbb{R}$, such that $\forall r \in B, Stab(r) = S$. We can also associate $Q = \mathbb{R}/S$ to the beat B.

The problem with this approach is that both S and Q are cyclic. So this approach is only good enough to assign cyclic symmetries to beats. Those are very simple and boring symmetries and I want to find a way to associate more complex groups to beats. The very nice things about these group is that they have a very natural definition. In some sense these groups capture the notion that a beat repeating 2 times in 4 is the same as a beat repeating 4 times in 8 or 6 times in 12. It only captures basic repetition information: how much time the beat is repeated and so the group is very small and simple.

We are only interested in recordings r such that there exists a smallest $a > 0$, such that $\forall x \in \mathbb{R}, r(a+x) = r(x)$.

### Playing Group

The **playing group** is the group of operations that one can make on the recordings. There are many operations that one can do, such as shifting the recording, inverting the recording, inverting 0 and 1 (interchanging the instruments), changing the speed of the recording. There are many different playing groups according to what operations we allow.

Here we consider the playing group as all the shifting of the recording, inverting of the recording and inverting the instruments. We do not consider yet change of the recording speed. We note $\forall t \in \mathbb{R}, D_t: F \rightarrow F$, the shift operations. We write $W: F \rightarrow F \\ r \mapsto 1-r$ for the swap operation that swap the instruments. Finally, we write 
$I: F \rightarrow F \\ r(x) \mapsto r(-x)$, for the inversion operation that inverts the recording around the origin.

**Inversion around c** where $c \in \mathbb{R}$. We check that $D_c \circ I \circ D_{-c}$ is the inversion around c. 
Indeed $[D_c \circ I \circ D_{-c}] (r) (x) = r(-x+2c)$ So that $[D_c \circ I \circ D_{-c}] (r) (c) = r(c)$, so the center of inversion is preserved, and $[D_c \circ I \circ D_{-c}] (r) (c+a) = r(-(c+a)+2c) = r(c - a)$, so that we can see that points are inversed around c.

The playing group is generated by $<D_t, W, I>$. We have $W \circ D_t = D_t \circ W$ and $W \circ I = I \circ W$ so that $<D_t, I> \oplus <W>$. We also have $[I \circ D_t \circ I] (r) (x) = r(x-t) = D_{-t}$. Finally the playing group is $<D_t, I \mid ID_tI = D_{-t}> \oplus <W> = \mathcal{P}$.

For any beat B, we can associate $Stab(B) \in \mathcal{P}$, the subgroup of P that maps B to itself.

### Point Group

The **point group** at $c \in \mathbb{R}$ of a recording r is $\{p \in <D_c \circ I \circ D_{-c}> \mid p \bullet r = r\}$.

W can never be in the point group, so the point group at c is always a subgroup of $<D_c \circ I \circ D_{-c}>$ which has only 2 elements.

The goal of this part is to define the structure of the point groups of a recording r.
The further goal is to associate to any beat B a point group.

Let's assume that the point groups at c and d, two distinct points on the real line are both non trivial.

To understand the reasoning let's assume that the pattern between c and d is 12345, we write is c12345d. We can see that from this pattern and the information that the point groups at c and d are not trivial we can reconstruct the whole recording.

c12345d --Ic-> 54321c12345d -Id-> 54321c12345d54321_12345 -Ic-> 54321_12345_54321c12345d54321_12345 -Id-> 
54321_12345_54321c12345d54321_12345_54321_12345

We observe the size of these:

1 --> 2 --> 4 --> 6 --> 8 --> ... 

Apart from the first step we can see that each step grows the sequence by 2 measures.

If we write 12345 as XY and 54321 as YX we can rewrite the sequence as:

cXYd --Ic-> YXcXYd -Id-> YXcXYdYX_XY -Ic-> YX_XY_YXcXYdYX_XY -Id-> 
YX_XY_YXcXYdYX_XY_YX_XY

It looks like this beat has a translation invariant pattern XYYX, that repeats every $2|c-d|$. Which would mean that a, the minimum repeating distance must divide $2|c-d|$. Finally $\exists k \in \mathbb{N}, |c-d| = k{a \over 2}$, in particular, $|c-d| \geq {a \over 2}$.

## Discrete case

$F_n = \{f: C(n) \rightarrow \mathcal{B}\}, \forall n \in \mathbb{N}$

The observation group of $F_n$ is C(n), and C(n) acts on $F_n$ via the following coaction 
$\bullet: F_n \times C(n) \rightarrow F_n \\ r \bullet g (i) \mapsto r(g + i)$

This is indeed a coaction because $r \bullet g \bullet h (i)= r(h + g + i) = r \bullet (g+h) (i)$

## Classifying the beats of F_n

Let r be a recording of F_n


